WebApp/Models/Rock.cs
using System;

namespace RocksInventory.Models
{
  public class Rock
  {
    public int Id { get; set; }
    public string Description { get; set; }
    public string Classification { get; set; }
    public int Hardness { get; set; }
    public string Color { get; set; }
    public DateTime Acquired { get; set; }
  }
}

WebApp/Models/RocksInventoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace RocksInventory.Models
{
  public class RocksInventoryContext : DbContext
  {
    public DbSet<Rock> Rocks { get; set; }

    public RocksInventoryContext(DbContextOptions options) : base(options) { }
  }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace RocksInventory.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

  }
}

WebApp/Controllers/RocksController.cs
using Microsoft.AspNetCore.Mvc;
using RocksInventory.Models;
using System.Collections.Generic;
using System.Linq;

namespace RocksInventory.Controllers
{
  public class RocksController : Controller
  {
    private readonly RocksInventoryContext _db;

    public RocksController(RocksInventoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Rock> model = _db.Rocks.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Rock rock)
    {
      _db.Rocks.Add(rock);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Rock thisRock = _db.Rocks.FirstOrDefault(item => item.Id == id);
      return View(thisRock);
    }
  }
}

WebApp/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the Rocks!</h1>
<p>@Html.ActionLink("See all rocks", "Index", "Rocks")</p> 

WebApp/Views/Rocks/Create.cshtml
<!-- prettier-ignore -->
@{ Layout = "_Layout"; } 

@using System;

@{ 
  var now   = @DateTime.Now; 
  var day   = now.Day.ToString();
  var month = now.Month.ToString();
  var year  = now.Year.ToString();
}
<!-- prettier-ignore-end -->

@model RocksInventory.Models.Rock

<h4>Add a new rock</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Description)
    @Html.TextBoxFor(model => model.Description)
    @Html.LabelFor(model => model.Classification)
    @Html.TextBoxFor(model => model.Classification)
    @Html.LabelFor(model => model.Hardness)
    @Html.EditorFor(model => model.Hardness, 
      new { htmlAttributes = new { 
        @type = "number", @min = "0", @max = "10", @step = "0.1", @value = "5.0" 
    }})
    @Html.LabelFor(model => model.Color)
    @Html.TextBoxFor(model => model.Color)
    @Html.LabelFor(model => model.Acquired)
    @Html.EditorFor(model => model.Acquired, 
      new { htmlAttributes = new { 
        @type="date", @value="@year-@month-@day"
    }})
    <input type="submit" value="Add new rock" />
}
<p>@Html.ActionLink("Show all rocks", "Index")</p>

WebApp/Views/Rocks/Details.cshtml
@{
  Layout = "_Layout";
}

@model RocksInventory.Models.Rock

<h2>Rock Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)<h3>
<h3>@Html.DisplayNameFor(model => model.Color): @Html.DisplayFor(model => model.Color)<h3>
<h3>@Html.DisplayNameFor(model => model.Hardness): @Html.DisplayFor(model => model.Hardness)<h3>
<h3>@Html.DisplayNameFor(model => model.Classification): @Html.DisplayFor(model => model.Classification)<h3>
<h3>@Html.DisplayNameFor(model => model.Acquired): @Html.DisplayFor(model => model.Acquired)<h3>
<p>@Html.ActionLink("Back to list", "Index")</p>

WebApp/Views/Rocks/Index.cshtml
@{  Layout = "_Layout"; }

@using RocksInventory.Models;
@using System.Reflection;

<h1>Items</h1>

@if (@Model.Count == 0)
{
  <h3>No items have been added yet!</h3>
} 
<div class="table-wrap">
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Classification</th>
        <th>Hardness</th>
        <th>Color</th>
        <th>Acquired</th>
      </tr>
    </thead>
    @foreach(Rock rock in Model)
    {
      <tr>
      @foreach (PropertyInfo pInfo in typeof(Rock).GetProperties())
      {
        if (pInfo.CanRead)
        {
          object value = pInfo.GetValue(rock, null);
          
          @if (pInfo.Name == "Id" || pInfo.Name == "Description")
          {
            <td>@Html.ActionLink($"{value}", "Details", new { id = rock.Id })</td>
          } else {
            <td>@value</td>
          }
        
        }
      }
      </tr>
    }
  </table>
</div>

<p>@Html.ActionLink("Add new item", "Create")</p>

WebApp/Views/Shared/Footer.cshtml
<footer>Bottom div content</footer>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>My rocks!</title>
    <!-- <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
    /> -->
    <link rel="stylesheet" href="~/styles/global.css" />
  </head>
  <body>
    <main>
      @RenderBody()
    </main>
    @Html.Partial("Footer")
  </body>
</html>